### ISSUE TITLE
测速没有速度

### ISSUE THREAD

**Issue by tdsq369** [sinspired/CloudflareBestIP#1]
很喜欢你的项目 但是我测速出来的结果都显示没有速度 
![1726855612731](https://github.com/user-attachments/assets/da88fb6f-d1ef-449d-84fa-645f17bbb882)

我已经使用了自定义测速节点

**Comment by sinspired** [comment]
看起来tcp延迟得到的结果就比较少，你尝试增加tcp和http延迟上限看看。

**Comment by sinspired** [comment]
刚更新了代码，你用新代码再尝试一下。
我自己使用默认设置测试是可以正常测速的。
![image](https://github.com/user-attachments/assets/83af8d84-6e01-4d0f-b054-1bd774fd9352)

**Comment by tdsq369** [comment]
![image](https://github.com/user-attachments/assets/e013a172-fff1-4fa4-9ea1-f2e00c4c796b)
有速度了 再次感谢你
