### ISSUE TITLE
其他系统版本的可以编译嘛

### ISSUE THREAD

**Issue by tdsq369** [sinspired/CloudflareBestIP#3]
其他系统版本的可以编译嘛

**Comment by sinspired** [comment]
go语言支持跨系统编译，不过main.go文件检测是否开启代理的函数使用了windows特有命令，估计在Linux系统会出错。你可以修改一下或者删除相关代码。

**Comment by sinspired** [comment]
已经支持跨平台编译，或下载1.4发布版本
