### ISSUE TITLE
设置了补偿系数还是会提示输入 这使得自动化变的困难

### ISSUE THREAD

**Issue by tdsq369** [sinspired/CloudflareBestIP#4]
![image](https://github.com/user-attachments/assets/76c23a6a-6478-4768-b573-47d75fe95ecb)
![image](https://github.com/user-attachments/assets/768f2aaf-4a06-4bd2-86a4-0204e407c593)
是我哪里设置错误吗?

**Comment by sinspired** [comment]
把下载协程数设为1就行了，你如果自动化没必要在乎这点时间。

**Comment by sinspired** [comment]
-speedtest设为1就行了
