### ISSUE TITLE
这是什么问题呢

### ISSUE THREAD

**Issue by Shillber** [sinspired/CloudflareBestIP#5]
![优效截图20241014094124](https://github.com/user-attachments/assets/be617d82-6385-4fdc-85a5-8668930b866c)
大佬，这是什么问题呢，用的1.3.3版本

**Comment by sinspired** [comment]
提问请提供具体参数，尝试用默认参数运行看看。可能因为你设置的outfilename吧？请查看readme.md说明，如果正确设置输入文档名，程序会自动设置输出文件名。

**Comment by Shillber** [comment]
> 提问请提供具体参数，尝试用默认参数运行看看。可能因为你设置的outfilename吧？请查看readme.md说明，如果正确设置输入文档名，程序会自动设置输出文件名。

只有 -countries="" -not="" -domain="" -token="" -api=""这几个没设置，其他的都设置的

**Comment by sinspired** [comment]
你想要在互联网解决问题，就要提供要求的信息，否则让人去猜你的问题吗？
不过，你把-outfile 参数去掉应该就可以了，参数设置格式请阅读readme.md

**Comment by Shillber** [comment]
> 你想要在互联网解决问题，就要提供要求的信息，否则让人去猜你的问题吗？ 不过，你把-outfile 参数去掉应该就可以了，参数设置格式请阅读readme.md

参数全部需要补全吗，用你提供的默认也是这样的

**Comment by sinspired** [comment]
“提供你设置的完整参数信息”，或者删掉所有参数信息再次运行。我们没有心灵感应，除非你提供，我不知道你运行程序时使用了什么参数或者你的电脑上发生了什么。

**Comment by Shillber** [comment]
> “提供你设置的完整参数信息”，或者删掉所有参数信息再次运行。我们没有心灵感应，除非你提供，我不知道你运行程序时使用了什么参数或者你的电脑上发生了什么。

./bestipTest -file=ip.txt -outfile="ipresult.csv" -port=443 -num=10 -speedlimit=1 -max=100 -speedtest=5 -tcplimit=5000 -httplimit=5000  -tls=true -url="speed.cloudflare.com/__down?bytes=500000000"

**Comment by sinspired** [comment]
删掉-outfile="ipresult.csv" ，或者修改成Result_filename.csv格式

**Comment by Shillber** [comment]
> 删掉-outfile="ipresult.csv" ，或者修改成Result_filename.csv格式

好的
